import { StyleSheet, Platform, StatusBar } from 'react-native';
import {
    BG_PRIMARY, BG_SURFACE, BG_ELEVATED,
    ACCENT_PRIMARY, ACCENT_LIGHT,
    TEXT_PRIMARY, TEXT_DIM, TEXT_HINT,
    SUCCESS_BG,
    DANGER_BG, DANGER_BORDER, DANGER_TEXT,
    BORDER_SUBTLE, BORDER_FAINT,
} from './theme';

export const styles = StyleSheet.create({
    // ── Confirmation phase ──────────────────────────────────────────────────────
    overlay: {
        flex: 1,
        backgroundColor: BG_PRIMARY,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 28,
    },
    confirmCard: {
        width: '100%',
        backgroundColor: BG_SURFACE,
        borderRadius: 24,
        padding: 28,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: BORDER_FAINT,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.4,
        shadowRadius: 16,
        elevation: 10,
    },
    warningIconWrap: {
        width: 72,
        height: 72,
        borderRadius: 36,
        backgroundColor: 'rgba(245, 158, 11, 0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        borderWidth: 1,
        borderColor: 'rgba(245, 158, 11, 0.22)',
    },
    confirmTitle: {
        color: TEXT_PRIMARY,
        fontSize: 20,
        fontWeight: '700',
        marginBottom: 10,
        letterSpacing: 0.3,
    },
    confirmText: {
        color: TEXT_DIM,
        fontSize: 14,
        textAlign: 'center',
        lineHeight: 22,
        marginBottom: 28,
    },
    confirmBtn: {
        width: '100%',
        backgroundColor: SUCCESS_BG,
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: 'center',
        marginBottom: 10,
    },
    confirmBtnDisabled: {
        backgroundColor: '#1e3a2a',
    },
    confirmBtnText: {
        color: TEXT_PRIMARY,
        fontSize: 15,
        fontWeight: '700',
    },
    confirmBtnTextDisabled: {
        color: '#4ade80',
        opacity: 0.5,
    },
    denyBtn: {
        width: '100%',
        backgroundColor: DANGER_BG,
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: DANGER_BORDER,
    },
    denyBtnText: {
        color: DANGER_TEXT,
        fontSize: 15,
        fontWeight: '700',
    },

    // ── QR Display phase ────────────────────────────────────────────────────────
    container: {
        flex: 1,
        backgroundColor: BG_PRIMARY,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 24) + 15 : 60,
        paddingBottom: 15,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: BORDER_SUBTLE,
    },
    backBtn: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: BG_ELEVATED,
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerTitle: {
        color: TEXT_PRIMARY,
        fontSize: 18,
        fontWeight: '700',
    },
    headerSpacer: {
        width: 44,
    },
    content: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 32,
        paddingBottom: 40,
    },
    identityBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: BG_ELEVATED,
        borderRadius: 20,
        paddingVertical: 10,
        paddingHorizontal: 16,
        marginBottom: 32,
        gap: 10,
    },
    identityIconWrap: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: '#0d1829',
        justifyContent: 'center',
        alignItems: 'center',
    },
    identityId: {
        color: ACCENT_LIGHT,
        fontSize: 15,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    qrWrapper: {
        padding: 16,
        backgroundColor: '#ffffff',
        borderRadius: 20,
        shadowColor: ACCENT_PRIMARY,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.25,
        shadowRadius: 20,
        elevation: 8,
        marginBottom: 28,
    },
    qrBox: {
        width: 200,
        height: 200,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    qrCornerMarker: {
        position: 'absolute',
        width: 36,
        height: 36,
        borderColor: '#1a202c',
        borderWidth: 4,
    },
    qrTL: { top: 0, left: 0, borderRightWidth: 0, borderBottomWidth: 0 },
    qrTR: { top: 0, right: 0, borderLeftWidth: 0, borderBottomWidth: 0 },
    qrBL: { bottom: 0, left: 0, borderRightWidth: 0, borderTopWidth: 0 },
    qrPlaceholderText: {
        color: TEXT_DIM,
        fontSize: 13,
        fontWeight: '600',
        textAlign: 'center',
        marginTop: 8,
    },
    hint: {
        color: TEXT_HINT,
        fontSize: 13,
        textAlign: 'center',
        lineHeight: 20,
    },
});
